languageCode = "en-us"
baseurl = "http://www.kytrinyx.com/"
title = "KYTRINYX"
sectionPagesMenu = "main"

[params]
  author = "Katrina Owen"

[permalinks]
  talk = "/talks/:slug"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "HOME"
  url        = "/"
  weight     = 0

  [[menu.main]]
  identifier = "talks"
  name       = "TALKS"
  url        = "/talks/"
  weight     = 2
